**Lab 1**

Using the dataset at https://bit.ly/2JIORnq
1. Assign it to a variable called users and use the 'user_id' as index
2. What is the age with least occurrence?
3. What is the mean age of users?
4. What is the most frequent occupation?

In [0]:
import pandas as pd
# reading csv file  
#readfile = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user") 
users = pd.read_csv("https://bit.ly/2JIORnq",sep='|')
print(users)
print("mean age of users")
mean1 = sum(users['age'])/len(users['age'])
print(mean1)
print("age least occurence")
leastoccur = users['age'].value_counts()
print(min(leastoccur.head(-1)))
print(leastoccur.tail(1))
print("most frequent occupation")
freqoccup = users['occupation'].value_counts()
print(freqoccup.head(1))

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]
mean age of users
34.05196182396607
age least occurence
1
7    1
Name: age, dtype: int64
most frequent occupation
student    196
Name: occupation, dtype: int64

In [0]:
import pandas as pd
a = pd.Series({'a':1,'b':2,'c':3})
a

a    1
b    2
c    3
dtype: int64

In [0]:
z = pd.Series({'x':1,'b':2,'y:':3,'d':4},
             index = ['b','x','d','f'])
z

b    2.0
x    1.0
d    4.0
f    NaN
dtype: float64

In [0]:
ages = np.random.randn(1100)*20+40
mask =  (ages > 8) & (ages < 100)
ages = pd.Series(ages(mask))
ages.size
bins = =0,18,35,60,100]
pd.cut(ages,bins,labels = ['children','adults','middleage','old'])
#------

In [0]:
data = {'state':['karnataka','UP'],'year':['2000','2001'],'pop':['skjdhf','sadf'],'debt':['99989','8000']}
frame = pd.DataFrame(data,columns = ['state','year','pop','debt'],index = ['i','ii','iii','iv','v','vi'])
frame

ValueError: ignored

**Lab 2**

Dataset: https://bit.ly/2UUomN0
1. What is the price of each item?
2. What was the quantity of the most expensive item ordered?
3. How many times were a Veggie Salad Bowl ordered?
4. How many times people ordered more than one Canned Soda?

In [0]:

#What is the price of each item?
#What was the quantity of the most expensive item ordered?
#quantity	item_name

import pandas as pd
# reading csv file  
userslab2 = pd.read_csv("https://bit.ly/2UUomN0",sep='\t')
print(userslab2)
userslab2['item_price']= userslab2['item_price'].map(lambda x: float(x.strip()[1:]))
#userslab2
print(userslab2[['item_name','item_price']])
if (userslab2 ['quantity'] > 1 ):
    unit_price = userslab2['item_price'] / userslab2['quantity']
elif (userslab2['quantity'] == 1):
      unit_price = userslab2['item_price']

print(unit_price)
sortedvalues = userslab2.sort_values()


#canned soda

#userslab2['quantity','item_price','item_name']
#userslab2['quantity','item_name','item_price']
#print(NameAndPrice)

      order_id  ...  item_price
0            1  ...      $2.39
1            1  ...      $3.39
2            1  ...      $3.39
3            1  ...      $2.39
4            2  ...     $16.98
...        ...  ...         ...
4617      1833  ...     $11.75
4618      1833  ...     $11.75
4619      1834  ...     $11.25
4620      1834  ...      $8.75
4621      1834  ...      $8.75

[4622 rows x 5 columns]
                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

TypeError: ignored

In [0]:

df = pd.DataFrame({'a':[1,2,3],'b': [4,5,6],'c':[7,8,9]})

print(df)
print(df-3)

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
   a  b  c
0 -2  1  4
1 -1  2  5
2  0  3  6

In [0]:
import pandas as pd
import numpy as np
a =pd.Series({'a':})

**Lab 3**

Dataset: https://bit.ly/1N5br3h
1. Assign Columns for the dataset 
2. Is there any missing value in the dataframe?
3. delete the column class
4. set the values of the rows 10 to 29 of the column 'petal_length' to NaN
5. Delete the rows that have NaN
6. Reset the index so it begins with 0 again
7. BONUS: Create & Answer your own question

In [0]:
import pandas as pd
# reading csv file  
userslab3 = pd.read_csv("https://bit.ly/1N5br3h",sep=',',names = ['petallength','petalwidth','plen','pwidth','class'])
print(userslab3)
Avgpetallength = sum(userslab3['petallength'])/len(userslab2['petallength'])
print("AVERAGEpetallength")
print(Avgpetallength)

Avgpetalwidth = sum(userslab3['petalwidth'])/len(userslab3['petalwidth'])
print("AVERAGEpetalwidth")
print(Avgpetalwidth)

Avgplen = sum(userslab3['plen'])/len(userslab3['plen'])
print("AVERAGEplen")
print(Avgplen)
Avgpwidth = sum(userslab3['pwidth'])/len(userslab3['pwidth'])
print("AVERAGEpwidth")
print(Avgpwidth)

     petallength  petalwidth  plen  pwidth           class
0            5.1         3.5   1.4     0.2     Iris-setosa
1            4.9         3.0   1.4     0.2     Iris-setosa
2            4.7         3.2   1.3     0.2     Iris-setosa
3            4.6         3.1   1.5     0.2     Iris-setosa
4            5.0         3.6   1.4     0.2     Iris-setosa
..           ...         ...   ...     ...             ...
145          6.7         3.0   5.2     2.3  Iris-virginica
146          6.3         2.5   5.0     1.9  Iris-virginica
147          6.5         3.0   5.2     2.0  Iris-virginica
148          6.2         3.4   5.4     2.3  Iris-virginica
149          5.9         3.0   5.1     1.8  Iris-virginica

[150 rows x 5 columns]
AVERAGEpetallength
5.843333333333335
AVERAGEpetalwidth
3.0540000000000007
AVERAGEplen
3.7586666666666693
AVERAGEpwidth
1.1986666666666672

In [0]:
userslab3.drop(["class"], axis = 1)

     petallength  petalwidth  plen  pwidth
0            5.1         3.5   1.4     0.2
1            4.9         3.0   1.4     0.2
2            4.7         3.2   1.3     0.2
3            4.6         3.1   1.5     0.2
4            5.0         3.6   1.4     0.2
..           ...         ...   ...     ...
145          6.7         3.0   5.2     2.3
146          6.3         2.5   5.0     1.9
147          6.5         3.0   5.2     2.0
148          6.2         3.4   5.4     2.3
149          5.9         3.0   5.1     1.8

[150 rows x 4 columns]

In [0]:
import pandas as pd
df =  pd.read_csv("https://bit.ly/1N5br3h",sep=',',names = ['petallength','petalwidth','plen','pwidth','class'])
df.isna()

     petallength  petalwidth   plen  pwidth  class
0          False       False  False   False  False
1          False       False  False   False  False
2          False       False  False   False  False
3          False       False  False   False  False
4          False       False  False   False  False
..           ...         ...    ...     ...    ...
145        False       False  False   False  False
146        False       False  False   False  False
147        False       False  False   False  False
148        False       False  False   False  False
149        False       False  False   False  False

[150 rows x 5 columns]

**Lab 4**

DataSet: https://bit.ly/2CudMVh
1. Assign it to a variable called drinks.
2. Which continent drinks more beer on average?
3. For each continent print the statistics for wine consumption.
4. Display the mean alcohol consumption per continent for every column.
5. Display the median alcohol consumption per continent for every column.
6. Display the mean, min and max values for spirit consumption.

In [3]:
import pandas as pd
# reading csv file  
drinks_userslab4 = pd.read_csv("https://bit.ly/2CudMVh")
print(drinks_userslab4)

         country  beer_servings  ...  total_litres_of_pure_alcohol  continent
0    Afghanistan              0  ...                           0.0         AS
1        Albania             89  ...                           4.9         EU
2        Algeria             25  ...                           0.7         AF
3        Andorra            245  ...                          12.4         EU
4         Angola            217  ...                           5.9         AF
..           ...            ...  ...                           ...        ...
188    Venezuela            333  ...                           7.7         SA
189      Vietnam            111  ...                           2.0         AS
190        Yemen              6  ...                           0.1         AS
191       Zambia             32  ...                           2.5         AF
192     Zimbabwe             64  ...                           4.7         AF

[193 rows x 6 columns]

In [8]:
#Which continent drinks more beer on average?
d2 = drinks_userslab4[['beer_servings','continent']].continent.value_counts();
print(d2)

AF    53
EU    45
AS    44
OC    16
SA    12
Name: continent, dtype: int64

In [11]:
d1 = drinks_userslab4.dropna(axis=0)
print(d1.groupby('continent').wine_servings.describe())

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

In [17]:
d6 = drinks_userslab4
print(d6.groupby('spirit_servings').spirit_servings.mean())

spirit_servings
0        0
1        1
2        2
3        3
4        4
      ...
302    302
315    315
326    326
373    373
438    438
Name: spirit_servings, Length: 109, dtype: int64

In [25]:
AvgofSpiritServings = sum(drinks_userslab4['spirit_servings'])/len(drinks_userslab4['spirit_servings'])

print("AVERAGEofSpritiServings")
print(AvgofSpiritServings)
print("MAXIMUMofSpiritiServings")
maximumofSpiritServings = max(drinks_userslab4['spirit_servings'])
print(maximumofSpiritServings)
print("MinimumofSpiritServings")
minimumofSpiritServings = min(drinks_userslab4['spirit_servings'])
print(minimumofSpiritServings)

AVERAGEofSpritiServings
80.99481865284974
MAXIMUMofSpiritiServings
438
MinimumofSpiritServings
0