**Lab 1**

Using the dataset at https://bit.ly/2JIORnq
1. Assign it to a variable called users and use the 'user_id' as index
2. What is the age with least occurrence?
3. What is the mean age of users?
4. What is the most frequent occupation?

In [0]:
import pandas as pd
users=pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user',sep=',',delimiter='|').set_index('user_id')
users

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

In [0]:
min_age=users['age'].min()
min_age

7

In [0]:
mean_age=users['age'].mean()
mean_age

34.05196182396607

In [0]:
freq_occupation=users['occupation'].max()
freq_occupation

'writer'

**Lab 2**

Dataset: https://bit.ly/2UUomN0
1. What is the price of each item?
2. What was the quantity of the most expensive item ordered?
3. How many times were a Veggie Salad Bowl ordered?
4. How many times people ordered more than one Canned Soda?

In [0]:
import pandas as pd
import numpy as np
users2=pd.read_csv('https://bit.ly/2UUomN0',delimiter='\t')
users2['item_price']=users2['item_price'].map(lambda x: float(x.strip()[1:]))
print(users2.iloc[users2.item_price.argmax()])

order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
Name: 3598, dtype: object

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: FutureWarning:
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  """

In [0]:
frequency_1=users2[users2["item_name"]=='Veggie Salad Bowl'].sum()
display(frequency_1['quantity'])

18

In [0]:
frequency_2=users2[users2["item_name"]=='Canned Soda'].groupby('item_name')['order_id'].value_counts().sum()
display(frequency_2)

104

**Lab 3**

Dataset: https://bit.ly/1N5br3h
1. Assign Columns for the dataset 
2. Is there any missing value in the dataframe?
3. delete the column class
4. set the values of the rows 10 to 29 of the column 'petal_length' to NaN
5. Delete the rows that have NaN
6. Reset the index so it begins with 0 again
7. BONUS: Create & Answer your own question

In [0]:
import pandas as pd
import numpy as np
users3=pd.read_csv('https://bit.ly/1N5br3h',sep=',',header=None)
users3=users3.set_axis(['sepal_length','sepal_width','petal_length','petal_width','class'],axis=1,inplace=False)
users3.isnull().any()
u1=users3.drop("class", axis=1)
users3['petal_width']
users3[10:29]=np.nan
u3=users3.dropna()
u4=u3.reset_index(0)
u4

     index  sepal_length  ...  petal_width           class
0        0           5.1  ...          0.2     Iris-setosa
1        1           4.9  ...          0.2     Iris-setosa
2        2           4.7  ...          0.2     Iris-setosa
3        3           4.6  ...          0.2     Iris-setosa
4        4           5.0  ...          0.2     Iris-setosa
..     ...           ...  ...          ...             ...
126    145           6.7  ...          2.3  Iris-virginica
127    146           6.3  ...          1.9  Iris-virginica
128    147           6.5  ...          2.0  Iris-virginica
129    148           6.2  ...          2.3  Iris-virginica
130    149           5.9  ...          1.8  Iris-virginica

[131 rows x 6 columns]

**Lab 4**

DataSet: https://bit.ly/2CudMVh
1. Assign it to a variable called drinks.
2. Which continent drinks more beer on average?
3. For each continent print the statistics for wine consumption.
4. Display the mean alcohol consumption per continent for every column.
5. Display the median alcohol consumption per continent for every column.
6. Display the mean, min and max values for spirit consumption.

In [1]:
import pandas as pd
drinks = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv",sep=',' )
drinks.head(60)

                     country  ...  continent
0                Afghanistan  ...         AS
1                    Albania  ...         EU
2                    Algeria  ...         AF
3                    Andorra  ...         EU
4                     Angola  ...         AF
5          Antigua & Barbuda  ...        NaN
6                  Argentina  ...         SA
7                    Armenia  ...         EU
8                  Australia  ...         OC
9                    Austria  ...         EU
10                Azerbaijan  ...         EU
11                   Bahamas  ...        NaN
12                   Bahrain  ...         AS
13                Bangladesh  ...         AS
14                  Barbados  ...        NaN
15                   Belarus  ...         EU
16                   Belgium  ...         EU
17                    Belize  ...        NaN
18                     Benin  ...         AF
19                    Bhutan  ...         AS
20                   Bolivia  ...         SA
21        Bosnia-Herzegovina  ...         EU
22                  Botswana  ...         AF
23                    Brazil  ...         SA
24                    Brunei  ...         AS
25                  Bulgaria  ...         EU
26              Burkina Faso  ...         AF
27                   Burundi  ...         AF
28             Cote d'Ivoire  ...         AF
29                Cabo Verde  ...         AF
30                  Cambodia  ...         AS
31                  Cameroon  ...         AF
32                    Canada  ...        NaN
33  Central African Republic  ...         AF
34                      Chad  ...         AF
35                     Chile  ...         SA
36                     China  ...         AS
37                  Colombia  ...         SA
38                   Comoros  ...         AF
39                     Congo  ...         AF
40              Cook Islands  ...         OC
41                Costa Rica  ...        NaN
42                   Croatia  ...         EU
43                      Cuba  ...        NaN
44                    Cyprus  ...         EU
45            Czech Republic  ...         EU
46               North Korea  ...         AS
47                  DR Congo  ...         AF
48                   Denmark  ...         EU
49                  Djibouti  ...         AF
50                  Dominica  ...        NaN
51        Dominican Republic  ...        NaN
52                   Ecuador  ...         SA
53                     Egypt  ...         AF
54               El Salvador  ...        NaN
55         Equatorial Guinea  ...         AF
56                   Eritrea  ...         AF
57                   Estonia  ...         EU
58                  Ethiopia  ...         AF
59                      Fiji  ...         OC

[60 rows x 6 columns]

In [2]:
more_avg_beer=drinks.groupby('continent').beer_servings.mean()
more_avg_beer.head(1)

continent
AF    61.471698
Name: beer_servings, dtype: float64

In [3]:
drinks.groupby('continent').wine_servings.mean()

continent
AF     16.264151
AS      9.068182
EU    142.222222
OC     35.625000
SA     62.416667
Name: wine_servings, dtype: float64

In [4]:
drinks.groupby('continent').total_litres_of_pure_alcohol.mean()

continent
AF    3.007547
AS    2.170455
EU    8.617778
OC    3.381250
SA    6.308333
Name: total_litres_of_pure_alcohol, dtype: float64

In [5]:
drinks.groupby('continent').total_litres_of_pure_alcohol.median()

continent
AF     2.30
AS     1.20
EU    10.00
OC     1.75
SA     6.85
Name: total_litres_of_pure_alcohol, dtype: float64

In [6]:
drinks.spirit_servings.mean()

80.99481865284974

In [7]:
drinks.spirit_servings.min(axis=0)

0

In [8]:
drinks.spirit_servings.max(axis=0)

438